#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 11 15:38:18 2022

@author: hannahtudo
"""
from realEstate import w3, load_contract, send_transaction, get_balance, getUsdWei, getCalendarEpoch

# %%
firstName = "Peter"
lastName = "Pan"
address = "0xB3D965D39cCD788A3cA4dAEa88E308aC832615aC"
tradeType = "Long"

limitPrice = "1000"
limitPrice = getUsdWei(int(limitPrice))

tradeLimit = "10000"
tradeLimit = getUsdWei(int(tradeLimit))

contractMonth = "1"
contractYear = "2023"
expDate = getCalendarEpoch(contractYear, contractMonth)

city = ['','Central Toronto', 'Central Toronto-Alexandra Park', 'Central Toronto-Bay Street Corridor', 'Central Toronto-Forest Hill',
        'Toronto Old York', 'Toronto Old York-Baby Point','Toronto Scarborough-Guildwood','Miami, FL', 'St.Petersburg, FL', 
        'Key West, FL', 'Los Angeles, CA', 'Anaheim, CA', 'Beverly Hills, CA', 'Manhattan, NY', 'Brooklyn, NY']

neighborhood = "Key West, FL"

# %%
contract = load_contract()

# Inputting user's entered info into the contract
txHash = contract.functions.SetUserInfo(
        firstName, lastName, address, tradeType, limitPrice, tradeLimit, expDate, neighborhood).transact(
            {'from': address, 'gas': 1000000}
            )
receipt = w3.eth.waitForTransactionReceipt(txHash)


#%%

transaction_hash = send_transaction(address, contract.address, tradeLimit)

# Display the Etheremum Transaction Hash

